services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=family_db'
      - 'POSTGRES_PASSWORD=smartguy'
      - 'POSTGRES_USER=smartguy'
    ports:
      - '9632:5432'
