services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=familyPortfolio_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=family'
    ports:
      - '7432:5432'
